<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenusTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('menus')->insert([
            [
                'id' => 1,
                'title' => 'Setting',
                'parent_id' => null,
                'route' => '#',
                'permission_class' => '["setting.show"]',
                'status' => 1,
                'icon' => 'fa-solid fa-gear',
                'options' => null,
                'admin_left_section' => 0,
                'top' => 0,
                'left' => 1,
                'footer' => 0,
                'order_by' => 20,
                'created_at' => '2025-11-11 08:21:47',
                'updated_at' => '2025-11-16 00:08:17',
            ],
            [
                'id' => 2,
                'title' => 'Menus',
                'parent_id' => 1,
                'route' => 'admin/menus',
                'permission_class' => '["menu.create","menu.delete","menu.update","menu.show"]',
                'status' => 1,
                'icon' => 'fas fa-bars',
                'options' => null,
                'admin_left_section' => 0,
                'top' => 0,
                'left' => 1,
                'footer' => 0,
                'order_by' => 1,
                'created_at' => '2025-11-12 00:43:22',
                'updated_at' => '2025-11-13 01:51:05',
            ],
            [
                'id' => 3,
                'title' => 'Roles',
                'parent_id' => 1,
                'route' => 'admin/roles',
                'permission_class' => '["role.create","role.delete","role.show","role.update"]',
                'status' => 1,
                'icon' => 'fas fa-users-line',
                'options' => null,
                'admin_left_section' => 0,
                'top' => 0,
                'left' => 1,
                'footer' => 0,
                'order_by' => 2,
                'created_at' => '2025-11-13 00:29:20',
                'updated_at' => '2025-11-15 23:59:21',
            ],
            [
                'id' => 4,
                'title' => 'Permissions',
                'parent_id' => 1,
                'route' => 'admin/permissions',
                'permission_class' => '["permission.create","permission.delete","permission.show","permission.update"]',
                'status' => 1,
                'icon' => 'fas fa-person-walking-luggage',
                'options' => null,
                'admin_left_section' => 0,
                'top' => 0,
                'left' => 1,
                'footer' => 0,
                'order_by' => 3,
                'created_at' => '2025-11-13 00:31:16',
                'updated_at' => '2025-11-15 23:59:48',
            ],
            [
                'id' => 5,
                'title' => 'Dashboard',
                'parent_id' => null,
                'route' => 'admin/dashboard',
                'permission_class' => '["dashboard.show"]',
                'status' => 1,
                'icon' => 'fas fa-bars-staggered',
                'options' => null,
                'admin_left_section' => 0,
                'top' => 0,
                'left' => 1,
                'footer' => 0,
                'order_by' => 1,
                'created_at' => '2025-11-13 02:28:02',
                'updated_at' => '2025-11-16 00:07:28',
            ],
            [
                'id' => 6,
                'title' => 'Users',
                'parent_id' => 1,
                'route' => 'admin/users',
                'permission_class' => '["user.create","user.delete","user.show","user.update"]',
                'status' => 1,
                'icon' => 'fas fa-users-gear',
                'options' => null,
                'admin_left_section' => 0,
                'top' => 0,
                'left' => 1,
                'footer' => 0,
                'order_by' => 4,
                'created_at' => '2025-11-13 02:40:41',
                'updated_at' => '2025-11-16 00:09:51',
            ],
            [
                'id' => 8,
                'title' => 'Docs',
                'parent_id' => 1,
                'route' => 'admin/docs',
                'permission_class' => '["docs.show"]',
                'status' => 1,
                'icon' => 'fas fa-book',
                'options' => null,
                'admin_left_section' => 0,
                'top' => 0,
                'left' => 1,
                'footer' => 0,
                'order_by' => 19,
                'created_at' => '2025-11-16 00:12:18',
                'updated_at' => '2025-11-16 00:21:05',
            ],
            [
                'id' => 9,
                'title' => 'Site Setting',
                'parent_id' => 1,
                'route' => 'admin/sitesettings',
                'permission_class' => '["show.sitesetting"]',
                'status' => 1,
                'icon' => 'fas fa-gears',
                'options' => null,
                'admin_left_section' => 0,
                'top' => 0,
                'left' => 1,
                'footer' => 0,
                'order_by' => 18,
                'created_at' => '2025-11-16 04:41:12',
                'updated_at' => '2025-11-16 04:41:12',
            ],
            [
                'id' => 10,
                'title' => 'GrapesJs',
                'parent_id' => 1,
                'route' => 'admin/grapesjs',
                'permission_class' => '["grapjs.create","grapjs.delete","grapjs.edit","grapjs.show"]',
                'status' => 1,
                'icon' => 'fas fa-champagne-glasses',
                'options' => null,
                'admin_left_section' => 0,
                'top' => 0,
                'left' => 1,
                'footer' => 0,
                'order_by' => 18,
                'created_at' => '2025-11-18 05:34:38',
                'updated_at' => '2025-11-18 05:34:38',
            ],
            [
                'id' => 11,
                'title' => 'Billing',
                'parent_id' => 1,
                'route' => 'admin/billing',
                'permission_class' => '["billing.create","billing.delete","billing.edit","billing.show"]',
                'status' => 1,
                'icon' => 'fas fa-file-invoice-dollar',
                'options' => null,
                'admin_left_section' => 0,
                'top' => 0,
                'left' => 1,
                'footer' => 0,
                'order_by' => 17,
                'created_at' => '2025-11-18 05:34:38',
                'updated_at' => '2025-11-18 05:34:38',
            ],
        ]);
    }
}